import pandas as pd
from pathlib import Path


configfile: "config/config.yaml"


df = pd.read_csv(config["samplesheet"], low_memory=False)[:10]

workflow_dir = Path("workflow").resolve()
RESULTS = Path("results").resolve()
ENVS = workflow_dir / "envs"
SCRIPTS = workflow_dir / "scripts"
RULES = workflow_dir / "rules"
LOGS = Path("logs/rules").resolve()
project_samples = sorted({(p, s) for p, s in zip(df["bioproject"], df["biosample"])})

target_files = set()
target_files.add(RESULTS / "metadata/metadata.tsv")


rule all:
    input:
        target_files,


include: RULES / "metadata.smk"
